-- ============================================================
-- FFC Shipments Management System
-- 20260101000004_public_reference_data.sql
--
-- SUPERSEDED — kept only so this filename isn't silently missing from
-- history. The anon-readable relaxation this file originally applied
-- (branches, countries, ports, airlines, freight_agents, clearing_agents,
-- carriers, courier_companies, shipment_categories, document_types,
-- currencies) now lives directly in 20260101000002_security_and_rls.sql,
-- consolidated there on purpose.
--
-- Why: this file and 0002 both defined policies on the same 11 tables —
-- 0002 with the original restrictive version, this file with a later
-- permissive one. Whichever ran LAST won, silently. When 0002 needed a
-- routine re-run in a later round (to update an unrelated function), it
-- re-created the restrictive policy AND its own "revoke all from anon"
-- statement stripped the anon grant this file had added — breaking
-- master-data dropdowns with no visible error. Splitting one logical
-- access decision across two files that could run in either order, any
-- number of times, was the actual bug. Consolidating them into one
-- authoritative definition removes the whole class of failure rather
-- than just this one instance of it.
--
-- Safe to run: does nothing.
-- ============================================================
select 1;
